FROM node:20-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

ARG VITE_API_WS_URL
ENV VITE_API_WS_URL=$VITE_API_WS_URL

EXPOSE 5173
CMD ["npm", "run", "dev"]